---
version: '3.9'

x-logging-rules: &logging-rules
  logging:
    driver: "json-file"
    options:
      max-size: 20m
      max-file: "5"

networks:
  app:
    driver: ${NETWORKS_DRIVER}

volumes:
  redis:
    driver: local

services:
  ### PHP-FPM ###
  php-fpm:
    build:
      context: ./deploy/php-fpm
      dockerfile: Dockerfile
    command: 'sh -c "cd /var/www/app && composer update && composer install --no-interaction --prefer-dist && php-fpm"'
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www/app
    env_file:
      - ${APP_CODE_PATH_HOST}/.env
    ports:
      - '8080:80'
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app
    <<: *logging-rules

  ### NGINX Server ###
  nginx:
    container_name: fibonacci_nginx
    image: nginx:1.19-alpine
    volumes:
      - ${APP_CODE_PATH_HOST}/deploy/nginx/conf.d/:/etc/nginx/conf.d/
      - ${APP_CODE_PATH_HOST}/deploy/nginx_logs:/var/log/nginx/
      - ${APP_CODE_PATH_HOST}:/var/www/app
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    restart: unless-stopped
    depends_on:
      - php-fpm
    networks:
      - app
    <<: *logging-rules

  ### Redis ###
  redis:
    container_name: fibonacci_redis
    image: redis:7.0.8
    command: redis-server --save 60 1 --loglevel warning
    restart: always
    env_file:
      - ${APP_CODE_PATH_HOST}/.env
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      timeout: 10s
      retries: 5
    networks:
      - app
    <<: *logging-rules
